wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.20
    start_time: 1749566135.401886
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 15
      - 16
      - 23
      4: 3.8.20
      5: 0.13.0
      8:
      - 5
curriculum_steps:
  desc: null
  value: 0
environment:
  desc: null
  value: harvest
influence_weight:
  desc: null
  value: 0.0
name:
  desc: null
  value: standard_a3c
num_agents:
  desc: null
  value: 5
num_episodes:
  desc: null
  value: 10000
seed:
  desc: null
  value: 0
visible_actions:
  desc: null
  value: false
